# docker-compose.yml
services:
  db_dev:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_DEV_USER}
      POSTGRES_PASSWORD: ${DB_DEV_PASS}
      POSTGRES_DB: ${DB_DEV_NAME}
    ports:
      - "${DB_DEV_PORT}:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
      - ./seed/init-common.sql:/docker-entrypoint-initdb.d/00-init-common.sql
      - ./seed/init-dev.sql:/docker-entrypoint-initdb.d/01-init-dev.sql

  db_prod:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_PROD_USER}
      POSTGRES_PASSWORD: ${DB_PROD_PASS}
      POSTGRES_DB: ${DB_PROD_NAME}
    ports:
      - "5433:5432" # Keep host port different if running both locally
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
      - ./seed/init-common.sql:/docker-entrypoint-initdb.d/00-init-common.sql
      - ./seed/init-pro.sql:/docker-entrypoint-initdb.d/01-init-pro.sql

volumes:
  pgdata_dev:
  pgdata_prod:
