version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    ports:
      - "2214:2214"
    depends_on:
      - db_dev
      - db_prod
    environment:
      DB_DEV_URL: postgresql://${DB_DEV_USER}:${DB_DEV_PASS}@${DB_DEV_HOST}:${DB_DEV_PORT}/${DB_DEV_NAME}
      DB_PROD_URL: postgresql://${DB_PROD_USER}:${DB_PROD_PASS}@${DB_PROD_HOST}:${DB_PROD_PORT}/${DB_PROD_NAME}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ${CODE_MOUNT}:/app
      - /app/node_modules
      - ./wait-for.sh:/wait-for.sh
    command: >
      /bin/sh -c "./wait-for.sh ${DB_DEV_HOST} true &&
                  ./wait-for.sh ${DB_PROD_HOST} true &&
                  ${START_CMD}"

  db_dev:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_DEV_USER}
      POSTGRES_PASSWORD: ${DB_DEV_PASS}
      POSTGRES_DB: ${DB_DEV_NAME}
    ports:
      - "${DB_DEV_PORT}:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
      - ./seed/init-common.sql:/docker-entrypoint-initdb.d/00-init-common.sql
      - ./seed/init-dev.sql:/docker-entrypoint-initdb.d/01-init-dev.sql

  db_prod:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_PROD_USER}
      POSTGRES_PASSWORD: ${DB_PROD_PASS}
      POSTGRES_DB: ${DB_PROD_NAME}
    ports:
      - "5433:5432" # Keep host port different if running both locally
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
      - ./seed/init-common.sql:/docker-entrypoint-initdb.d/00-init-common.sql
      - ./seed/init-pro.sql:/docker-entrypoint-initdb.d/01-init-pro.sql

volumes:
  pgdata_dev:
  pgdata_prod:
